/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
// fonts:
//  - family:  MyFlutterApp
//    fonts:
//     - asset: fonts/MyFlutterApp.ttf
///
///
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class VIcons {
  VIcons._();

  static const _kFontFam = 'VIcons';

  // Icons source http://fluttericon.com/

  static const IconData retweet = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe801, fontFamily: _kFontFam);
}
